name: assignment-test
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "*"
jobs:
  full-test:
    container: cuaesd/aesd-autotest:assignment5-buildroot
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run full test
        env:
          GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
        run: ./full-test.sh
      - name: Cleanup
        if: always()
        run: |
          ssh-add -D

